let pl: (Int, Int) = (1,2)
let x: (Bool, String) = (false, "Image no longer exists at URL")
let person = (name: "jim", age: 30)
print("\(person.name)'s age is \(person.age)")
var person2 = (name: "Jim", age: 30)
print("\(person2.name)'s age is \(person2.age)")
